name: 'sls-helper'
description: 'Vaildates and deploys sls functions'
branding:
  icon: 'check'
  color: 'green'

inputs:
  changes:
    description: 'Path or space-separated list of paths of files changed'
    required: true 
  mode:
    description: 'Mode of eb7-sls-helper; valid choices are: validate, deploy, test and tox'
    required: true 
  stage:
    description: 'Function stage to deploy to'
    required: true
  profile:
    description: 'AWS profile to deploy to'
    required: true
  validator_path:
    description: 'Function stage to deploy to'
    required: false 
    default: ''
  loglevel:
    description: 'Loglevel of output'
    required: false
    default: 10
  aws_key:
    description: 'AWS KEY'
    required: true
  aws_secret:
    description: 'AWS SECRET KEY'
    required: true
  postman_api_key:
    description: 'API key for postman account'
    required: false 

outputs:
  formatted:
    description: 'Formatted output for github'

runs:
  using: 'docker'
  image: 'Dockerfile'
