"""Formats (and sanitizes) tox output to prevent leaking access tokens."""

import re

# @ReviewDog - This is a password regex, not an actual password
URL_WITH_ACCESS_TOKEN_REGEX = r"https:\/\/([a-z0-9]+)@github.com"  # noqa: S105


def format_tox_output(output: bytes) -> str:
    """Function for formatting tox output.

    Right now, it only sanitizes the access token but
    but it can be extended in the future to support extra formatting.
    We have an unreadable format at the moment.

    Arguments:
        output: original output generated by tox

    Returns:
        sanitized: tox output sanitized
    """

    string_output = str(output)
    formatted_output = string_output.replace('\\n', '\n').replace('\\t', '\t')
    regex = re.compile(URL_WITH_ACCESS_TOKEN_REGEX)
    return re.sub(regex, "sanitized_url :)", formatted_output)
