"""Formats (and sanitizes) tox output to prevent leaking access tokens."""

import re

# @ReviewDog - This is a password regex, not an actual password
URL_WITH_ACCESS_TOKEN_REGEX = r"https:\/\/([a-z0-9]+)@github.com"  # noqa: S105


def format_tox_output(output: bytes) -> str:
    """Function for formatting tox output.

    Right now, it only sanitizes the access token but
    but it can be extended in the future to support extra formatting.
    We have an unreadable format at the moment.

    Arguments:
        output: original output generated by tox

    Returns:
        sanitized: tox output sanitized
    """
    string_output = output.decode("utf8")
    sanitized_str = sanitize_str(string_output)
    return sanitized_str


def sanitize_str(text: str) -> str:
    """Function for sanitizing string from  secret keys

    Args:
        text (str): output log for tox

    Returns:
        str: sanitized string from  secret keys
    """
    regex = re.compile(URL_WITH_ACCESS_TOKEN_REGEX)
    return re.sub(regex, "sanitized_url :)", text)


def get_list_from_string(text: str) -> list:
    """Function for getting an itterable list out of a multiline string

    Args:
        text (str): multiline string

    Returns:
        list: a list containing lines of string 
    """
    return text.splitlines()


def add_color_markdown(log_text: str) -> str:
    """[summary]

    Args:
        log_text ([type]): [description]

    Returns:
        str: [description]
    """
    
    return "```diff\n+ " + log_text + "\n```\n"


def split_success_logs(output_logs: str) -> list:
    """Function for splitting respective parts of logs

    Args:
        output_logs (str): the full text output

    Returns:
        list: list containing different parts of logs
    """
    flags = re.DOTALL | re.MULTILINE
    installtion_logs = output_logs.split("----------- coverage", 1)[0]
    tests_logs = re.findall('((^-.*coverage).*?^(_.*summary.*_$))', output_logs, flags)[0][0]
    final_logs = re.findall('(^  py38.*)', output_logs, flags)[0]
    log_list = {"general": installtion_logs, "tests": tests_logs, "final": final_logs}
    for key, value in log_list.items():
        colorized_log = add_color_markdown(value)
        log_list[key] = colorized_log
        print(colorized_log)
    # print(log_list)